### ISSUE TITLE
mpi4py requirement in requirements.txt may break things

### ISSUE THREAD

**Issue by bueler** [StefanoFochesatto/VI-AMR#2]
I am **not** sure of my diagnosis here.  However, I ran `pip install -r requirements.txt` and then it caused mpi4py errors until I wiped my firedrake install and started over.

**Comment by StefanoFochesatto** [comment]
Are you familiar with [uv?](https://docs.astral.sh/uv/). I just started using it, I found it from this [video](https://youtu.be/gSKTfG1GXYQ). I just pushed a new requirement.txt and it seems to work. Maybe parallel test next?

**Comment by bueler** [comment]
I would encourage you not to have automated requirements here, and not to add yet another dependency, i.e. on uv.  Only your figure-generation stuff needs it, right?  The issue is that you break peoples Firedrake venv if you conflict with the mpi4py and numpy in their Firedrake install.  (Or any other packages that overlap.)  The safest thing for VI-AMR to do is to state in the README what extra packages are used by which scripts, and not be specific about versions unless you have a very precise need.  Maintain VI-AMR based on _you_ having up-to-date packages.  I would isolate your figure generation and study scripts and examples into a directory with its own README, where the requirements for that are stated.  Your core VI-AMR functionality can be used by people as a library with no additional requirements beyond `firedrake-install --netgen`, as far as I can tell?  Keep it that way?

**Comment by bueler** [comment]
the uv video was great.  But don't play a hard game if you can just skip the game?

**Comment by StefanoFochesatto** [comment]
Ahh separating the figure and study scripts is a great idea, and what you are saying about core VI-AMR is correct; no additional requirements. You're right uv is relatively fancy tooling and we don't need it.

**Comment by StefanoFochesatto** [comment]
Also for what it's worth, a pip install of firedrake is coming and installing with uv will probably be recommended (per Lawrence): 
[https://github.com/firedrakeproject/firedrake/discussions/3894](https://github.com/firedrakeproject/firedrake/discussions/3894)

**Comment by bueler** [comment]
Cool.  Nice catch.  And I'm really glad to see Lawrence is still active on this.
