### ISSUE TITLE
convoluted install to get animate and netgen

### ISSUE THREAD

**Issue by bueler** [StefanoFochesatto/VI-AMR#6]
When I do
```
git clone https://github.com/mesh-adaptation/animate.git
cd animate
unset PETSC_DIR;  unset PYTHONPATH
make install
```
and then try to use animate (activate new venv etc.) it reports that my petsc install missed `--download-mmg`.  That's kind of critical for animate.  Looking into their repo, the sole pip info file (`pyproject.toml`) does not include the --download-mmg requirement anywhere.   The haven't tried their own pip install on a fresh machine I suppose?

Next try is to grab the Makefile which actually includes the correct petsc install options (see https://github.com/mesh-adaptation/docs/wiki/Installation-Instructions):
```
git clone https://github.com/mesh-adaptation/animate.git
cd animate/
curl -O https://raw.githubusercontent.com/mesh-adaptation/mesh-adaptation-docs/main/install/Makefile
curl -O https://raw.githubusercontent.com/mesh-adaptation/mesh-adaptation-docs/main/install/petsc_configure_options.txt
unset PETSC_DIR;  unset PYTHONPATH
make install
```
Now I can use animate, but the firedrake install does not include --netgen.  But if you go into the (animate) venv and run `bin/firedrake-update --netgen` then you do get netgen but you lose animate; python can no longer find it.

Currently trying
```
git clone https://github.com/mesh-adaptation/animate.git
cd animate/
curl -O https://raw.githubusercontent.com/mesh-adaptation/mesh-adaptation-docs/main/install/Makefile
curl -O https://raw.githubusercontent.com/mesh-adaptation/mesh-adaptation-docs/main/install/petsc_configure_options.txt
unset PETSC_DIR;  unset PYTHONPATH
#    hand edit Makefile: add this as line 33:
#         FIREDRAKE_CONFIGURE_OPTIONS += "--netgen"
make install
```
but of course I am waiting for another petsc install.

Summary:  I don't think the animate people know what they are doing with respect to the firedrake install process.  Their wiki is all over the place.  It does not acknowledge what their new Makefile actually does, namely pip install without paying attention to the need for special petsc config.

I think you (Stefano) may have benefitted from a prior animate install generating a petsc install that actually has mmg?  Note that recent Firedrake *does not* have an mmg dependency; perhaps it used to.

**Comment by StefanoFochesatto** [comment]
What you are saying about my install is accurate. I think it is likely that after this new petsc install you will have to clone the animate repo and run make, while in the new firedrake env.
